name       : haskell-project-template
version    : 0.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/project-template-0.2.0/project-template-0.2.0.tar.gz : aeabd7d1785b31abaffc78f02d9dda67d57d01822755f09614bfc65e99506310
license    : BSD-3-Clause
component  : programming.haskell
summary    : Templates for new Haskell projects
description: |
    Templates for new Haskell projects
builddeps  :
    - haskell-cabal-install
    - haskell-conduit-extra
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
