name       : haskell-project-template
version    : 0.2.0.1
release    : 2
source     :
    - http://hackage.haskell.org/package/project-template-0.2.0.1/project-template-0.2.0.1.tar.gz : eb52496fa7448f5fed445525c05327b31a45282fc1d0a772c7022a9809e7c9dc
license    : BSD-3-Clause
component  : programming.haskell
summary    : Templates for new Haskell projects
description: |
    Templates for new Haskell projects
builddeps  :
    - haskell-base64-bytestring
    - haskell-cabal-install
    - haskell-conduit-extra
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
