name       : haskell-project-template
version    : 0.2.1.0
release    : 3
source     :
    - https://hackage.haskell.org/package/project-template-0.2.1.0/project-template-0.2.1.0.tar.gz : 2d99e5bf750e409d8f2daa2a9038ce39c40c310e2e52076549659968461f8429
license    : BSD-3-Clause
component  : programming.haskell
summary    : Templates for new Haskell projects
description: |
    Templates for new Haskell projects
builddeps  :
    - haskell-base64-bytestring-devel
    - haskell-cabal-install
    - haskell-conduit-extra-devel
rundeps    :
    - devel:
        - haskell-base64-bytestring-devel
        - haskell-conduit-extra-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
